---
abstract: "A Perl wrapper around OpenSSL's AES library"
author:
  - 'Tolga Tarhan'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.64, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Crypt-OpenSSL-AES
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.008'
resources:
  repository: git://github.com:perl-openssl/perl-Crypt-OpenSSL-AES.git
version: '0.06'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
