---
abstract: "A Perl wrapper around OpenSSL's AES library"
author:
  - 'Tolga Tarhan <cpan at ttar dot org>'
build_requires:
  Crypt::CBC: '0'
  Crypt::Cipher::AES: '0'
  Crypt::Digest::SHA512_256: '0'
  Crypt::Mode::CBC: '0'
  Crypt::Mode::CFB: '0'
  Crypt::Mode::CTR: '0'
  Crypt::Mode::ECB: '0'
  Crypt::Mode::OFB: '0'
  Crypt::OpenSSL::Guess: '0'
  Crypt::PRNG: '0'
  Digest::SHA: '0'
  MIME::Base64: '0'
  Test::More: '0'
configure_requires:
  Crypt::OpenSSL::Guess: '0'
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.030, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Crypt-OpenSSL-AES
provides:
  Crypt::OpenSSL::AES:
    file: lib/Crypt/OpenSSL/AES.pm
    version: '0.11'
requires:
  Exporter: '0'
  XSLoader: '0'
  perl: '5.008'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Crypt-OpenSSL-AES
  homepage: http://search.cpan.org/dist/Crypt-OpenSSL-AES/
  repository: git://github.com/perl-openssl/perl-Crypt-OpenSSL-AES.git
version: '0.11'
x_generated_by_perl: v5.36.1
x_maintainers:
  - 'Timothy Legge <timlegge@cpan.org>'
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
